services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
     - "443:443/tcp"
    restart: always
    volumes:
     - openvpn-etc:/etc/openvpn

volumes:
  openvpn-etc:
